on:
  push:
    branches: ['master']

jobs:
  # `build` is a user-defined name for this job
  push:
    # Set the base environment to run the Action on
    runs-on: ubuntu-latest

    steps:
      - name: Step 1 - Git checkout
        uses: actions/checkout@v1

      - name: Step 2 - echo Branch name
        run: echo running on branch ${GITHUB_REF##*/}

      - name: Login to Registry
        uses: docker/login-action@v1
        with:
          registry: registry.willemserruys.com
          username: ${{ secrets.REGISTRY_USERNAME }}
          password: ${{ secrets.REGISTRY_PASSWORD }}

      - name: Step 3 - Build build image
        run: docker build -f EntityFrameworkCore.Examples.Web/Dockerfile . -t registry.willemserruys.com/efcore_test:latest

      - name: Step 4 - Push image
        run: docker push registry.willemserruys.com/efcore_test:latest

    