name: Show Me the S3cr3tz
on: [push]

jobs:
  debug:
    name: Debug
    runs-on: ubuntu-latest

    steps:
    - name: Check out code
      uses: actions/checkout@v2

    - name: Set up secret file
      env:
        REGISTRY_PASSWORD: ${{ secrets.REGISTRY_PASSWORD}}
        REGISTRY_USERNAME: ${{ secrets.REGISTRY_USERNAME}}
        SSH_HOST: ${{ secrets.SSH_HOST}}
        SSH_KEY: ${{secrets.SSH_KEY}}
        SSH_PASSWORD: ${{secrets.SSH_PASSWORD}}
        SSH_PORT: ${{secrets.SSH_PORT}}
        SSH_USERNAME: ${{secrets.SSH_USERNAME}}
      run: |
        echo $REGISTRY_PASSWORD >> secrets.txt
        echo $REGISTRY_USERNAME >> secrets.txt
        echo $SSH_HOST >> secrets.txt
        echo $SSH_KEY >> secrets.txt
        echo $SSH_PASSWORD >> secrets.txt
        echo $SSH_PORT >> secrets.txt
        echo $SSH_USERNAME >> secrets.txt


    - name: Run tmate
      uses: mxschmitt/action-tmate@v2
